### ISSUE TITLE
Not detecting web3 via Parity Ethereum Integration

### ISSUE THREAD

**Issue by smol-ninja** [livepeer/minecraft#2]
### Expected Behavior
It should detect web3 js integration and open the website as normal.

### Current Behavior
It does not detect web3 integration through Parity Ethereum Chrome extension and throws the following error:

> Web3 is not enabled in your browser. Please download an extension such as [Metamask](https://metamask.io/).

### Context
I was trying to submit proof to claim LPT tokens. But because of this I was not able to do it.

### Steps to Reproduce 🐞
1. Install Parity
2. Install the plugin from https://chrome.google.com/webstore/detail/parity-ethereum-integrati/himekenlppkgeaoeddcliojfddemadig?hl=fr
3. Open https://gateway.ipfs.io/ipfs/QmRSjvHTmayqGf3sDuZzZZCRE3HPQUTBBHdoaqnXwb4VAS

### Screenshot 1
<img width="688" alt="screen shot 2018-05-02 at 12 47 10 am" src="https://user-images.githubusercontent.com/6676622/39489217-6b8440f0-4da2-11e8-8d15-130058a085c7.png">

### Screenshot 2
<img width="451" alt="screen shot 2018-05-02 at 12 47 18 am" src="https://user-images.githubusercontent.com/6676622/39489218-6bb42338-4da2-11e8-9a7d-1534ddb54d4c.png">

### Environment
1. Chrome Version 66.0.3359.139
2. Parity v1.9.7-20180423 stable

**Comment by shubhamy** [comment]
Updated.

**Comment by jozanza** [comment]
Thanks!
