### ISSUE TITLE
Can I choose the amount of token I want to generate ?

### ISSUE THREAD

**Issue by nelaturuk** [livepeer/minecraft#6]
Hi, 

I haven't tested the dapp yet. But a general question. Do i get to choose how much LPT token I want to mine from the account address ? Or does it submit proof for all the ether ? 

Thanks. 

Regards, 
Keerthi.

**Comment by dob** [comment]
If you're considering this a general purpose tool, then at the moment the
tool just submits the proof for the one account you've included, and the
amount you mine will be determined by the algorithm in the underlying smart
contract. However if you're asking specifically about the Livepeer Token
MerkleMine, note that the MerkleMine completed a few months ago, as there
are no available unclaimed proofs left to submit.

**Comment by nelaturuk** [comment]
Got it thanks.
